import 'package:flutter/cupertino.dart';

class vidio_provider extends ChangeNotifier {
  List vidioList = [
    "assets/images/1.jpg",
   "assets/images/2.jpg",
    "assets/images/3.jpg",
    "assets/images/4.jpg",
   "assets/images/5.jpg",
   "assets/images/6.jpg",
    "assets/images/7.jpg",
    "assets/images/8.jpg",
    "assets/images/9.jpg",
    "assets/images/10.jpg",
    "assets/images/11.jpg",
    "assets/images/12.jpg",
    "assets/images/13.jpg",
    "assets/images/14.jpg",
    "assets/images/15.jpg",
    "assets/images/16.jpg",
    "assets/images/17.jpg",
    "assets/images/18.jpg",
    "assets/images/19.jpg",
    "assets/images/20.jpg",
    "assets/images/21.jpg",
    "assets/images/22.jpg",
    "assets/images/23.jpg",
    "assets/images/24.jpg",
    "assets/images/25.jpg",
  ];

  List duretion = [
    5,
    7,
    9,
    1,
    2,
    7,
    9,
    11,
    14,
    17,
    13,
    18,
    14,
    1,
    1,
    2,
    4,
    4,
    1,
    5,
    1,
  ];

  List <String> name = [
    "Endeavour 1",
    "Endeavour 2",
    "Endeavour 3",
    "Endeavour 4",
    "creta 5",
    "thar 6",
    "thar 7",
    "thar 8",
    "thar 9",
    "thar 10",
    "thar 11",
    "thar 12",
    "thar 13",
    "thar 14",
    "thar 15",
    "thar 16",
    "thar 17",
    "thar 18",
    "thar 19",
    "thar 20",
    "thar 21"
  ];
}